#开发环境配置
server:
  port: 8205
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /websocket
#日志配置
logging:
  level:
    root: debug
    org:
      springframework: warn
      spring:
        springboot:
          dao: debug