spring:
  mail: #邮箱配置
    # SMTP 服务器地址
    host: smtp.sina.com
    # SMTP 服务弃登录用户账号
    username: dllwhcrawler@sina.com
    # SMTP 服务弃登录用户密码
    password: b89d3a0b8c46d445
    # 编码格式
    default-encoding: UTF-8
    properties:
      mail:
        recipient: duleilewuhen@sina.com
        auth: true
        starttls:
          enable: true
          required: true

logging: # 日志级别从低到高分为：trace < debug < info < warn < error < fatal
  level: # 日志级别控制前缀
    root: info # 控制root 的日志级别为debug以上