server:
  port: 8223
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: info
    com.dllwh.dao.*: debug
    org:
      springframework: info
spring:
  application:
    name: SpringBoot2-chapter23-aop
  devtools: # 设置热部署
    restart: 
      enabled: true #开启热部署
      additional-paths: src/main/java # 重启范围
      exclude: webviews/,static/ # classpath目录下的webviews文件夹内容修改不重启
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://rm-duleilewuhen.mysql.rds.aliyuncs.com:3306/spring?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username:  spring
    password:  spring
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  type-aliases-package: org.dllwh.aop.model
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations:
    - classpath:org/dllwh/aop/dao/impl/*Mapper.xml