server:
  port: 8216
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

logging: # 日志级别从低到高分为：trace < debug < info < warn < error < fatal
  level: # 日志级别控制前缀
    root: info # 控制root 的日志级别为debug以上
    org:
      springframework: info #控制org.springframework包下的日志级别为info以上

spring:
  application:
    name: SpringBoot2-chapter-vue
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths:
        - src/main/java
      exclude: templates/** # #classpath目录下的webviews文件夹内容修改不重启
  profiles:
    active:
      - datasource # 数据库配置
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    enable-spring-el-compiler: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss