spring:
  datasource:
    url: jdbc:mysql://rm-duleilewuhen.mysql.rds.aliyuncs.com:3306/spring?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: spring #数据库登录账号
    password: spring #数据库登录密码
    driver-class-name: com.mysql.jdbc.Driver
---
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:org/dllwh/dao/*.xml
  # 搜索指定包别名
  type-aliases-package: org.dllwh.entity
