#### redis 配置
spring: 
  redis: 
    database: 0 #Redis数据库索引（默认为0）
    host:  127.0.0.1 # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 10000 ####客户端超时时间单位是毫秒 默认是2000
    pool: 
      max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
      min-idle: 1 # 连接池中的最小空闲连接
      max-idle: 20 # 连接池中的最大空闲连接
      max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 1024 #连接池的最大数据库连接数。设为0表示无限制
        min-idle: 1 # 连接池中的最小空闲连接
        max-idle: 20 #最大空闲数
        max-wait: 10000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
    cluster: 
      nodes: 集群节点连接地址
    sentinel: 
      nodes: 节点连接地址
      master: mymaster