server:
  port: 8766
spring:
  application:
    name: GateWayApplication
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a: ## 以/api-a/ 开头的请求都转发给service-ribbon服务
      path: /api-a/**
      serviceId: ribbonConsumerApplication
    api-b:
      path: /api-b/** ## 以/api-b/开头的请求都转发给service-feign服务
      serviceId: feignConsumerApplicatin