server:
  port: 8761
eureka:
  instance:
    ## 指定了Eureka服务端的IP
    hostname: localhost
  client:
    ## 表示是否将服务注册到Eureka服务端，由于自身就是Eureka服务端，所以设置为false；
    register-with-eureka: false 
    ## 是否从Eureka服务端获取服务信息，因为这里只搭建了一个Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false；
    fetch-registry: false 
    serviceUrl:
    ## 指定Eureka服务端的地址，默认值为http://localhost:8761/eureka。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java