server:
  port: 8216
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
spring:
  application:
    name: SpringBoot2-chapter-vue
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths:
        - src/main/java
      exclude: templates/** # #classpath目录下的webviews文件夹内容修改不重启
  profiles:
    active:
      - datasource # 数据库配置
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    enable-spring-el-compiler: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8