server:
  port: 8221
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: info
    org:
      springframework: info
spring:
  application:
    name: SpringBoot2-chapter21-mybatisPlus
  devtools: # 设置热部署
    restart: 
      enabled: true #开启热部署
      additional-paths: src/main/java # 重启范围
      exclude: webviews/,static/ # classpath目录下的webviews文件夹内容修改不重启
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://rm-duleilewuhen.mysql.rds.aliyuncs.com:3306/spring?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username:  spring
    password:  spring
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath:org/dllwh/mybatisPlus/dao/impl/*Mapper.xml 
  type-aliases-package: org.dllwh.mybatisPlus.entity