server:
  port: 8220
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: info
    org:
      springframework: info
spring:
  application:
    name: SpringBoot2-chapter20-freeMarker
  datasource:
    url: jdbc:mysql://rm-duleilewuhen.mysql.rds.aliyuncs.com:3306/db_wechat?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: product
    password: product
    driver-class-name: com.mysql.jdbc.Driver
  devtools: # 设置热部署
    restart: 
      enabled: true #开启热部署
      additional-paths: src/main/java # 重启范围
      exclude: webviews/,static/ # classpath目录下的webviews文件夹内容修改不重启
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/webviews/
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.dllwh.model

swagger: # 是否开启swagger，正式环境一般是需要关闭的，可根据springboot的多环境配置进行设置
  enabled: true 