spring:
  datasource:
    url: jdbc:mysql://rm-2zevys7thq96t31s4no.mysql.rds.aliyuncs.com:3306/db_wechat?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    enable-spring-el-compiler: false
    prefix: classpath:/webviews/
    suffix: .html
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml,classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.cdeledu.domain