#开发环境配置
server:
  port: 8214
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
#日志配置
logging:
  level:
    root: debug
    org:
      springframework: warn
      spring:
        springboot:
          dao: debug
#Spring配置
spring: 
  profiles:
    active:
      - datasource # 数据库配置
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths:
        - src/main/java
      exclude: webviews/** # #classpath目录下的webviews文件夹内容修改不重启
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    enable-spring-el-compiler: false
    prefix: classpath:/webviews/
    suffix: .html
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    timeout: 0 # 连接超时时间（毫秒）