### 是否显示banner，可选值[log|OFF]
spring: 
  main: 
    banner-mode: log
---
### 全局异常处理
server:
  error:
    include-stacktrace: ALWAYS
    path: exception
  tomcat:
    uri-encoding: UTF-8
#### 数据库配置
spring: 
  datasource: 
    url: jdbc:mysql://rm-2zevys7thq96t31s4no.mysql.rds.aliyuncs.com:3306/db_wechat?useUnicode=true&amp;characterEncoding=UTF-8
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      filters: stat,wall,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      initial-size: 5
      min-idle: 5
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
      connection-properties:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 # 通过connectProperties属性来打开mergeSql功能；慢SQL记
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      reset-stat-enable: true #允许清空统计数据 
      filter: 
        stat:
          enabled: true 
          log-slow-sql: true
        wall: #配置wall filter
          enabled: true
          config:
            truncate-allow: false 
        slf4j: # 配置日志输出
         enabled: true
         statement-create-after-log-enabled: false
         statement-close-after-log-enabled: false
         result-set-open-after-log-enabled: false
         result-set-close-after-log-enabled: false
      stat-view-servlet: # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        enabled: true
        login-username: admin #登录账号
        login-password: admin #登录密码
        reset-enable: false #是否能够重置数据
        url-pattern: /druid/*
        allow:  #白名单;为空则允许全部
        deny: #IP黑名单 (存在共同时，deny优先于allow)
      web-stat-filter: # 配置WallFilter
        enabled: true  #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
        session-stat-enable: true  #session统计功能
---
#### Thymeleaf 配置
spring:
  thymeleaf:
    cache:  false ## 关闭缓存，便于在热部署文件，页面不产生缓存，能及时更新
    #prefix: classpath:/thymeleaf/ #添加路径前缀
    prefix: classpath:/templates/ #默认配置可以不用添加
    suffix: .html #默认属性是 .html，可以不用添加
    encoding: UTF-8 #编码格式
---
#### mybatis
mybatis: 
  mapperLocations: classpath:com/cdeledu/dao/impl/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
---
#### redis主从配置
#spring: 
#  redis: 
#    database: 0 #Redis数据库索引（默认为0）
#    host:  127.0.0.1 # Redis服务器地址
#    port:  6379 # Redis服务器连接端口
#    password:  # Redis服务器连接密码（默认为空）
#    timeout: 10000 ####客户端超时时间单位是毫秒 默认是2000
#    pool: 
#      max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
#      min-idle: 1 # 连接池中的最小空闲连接
#      max-idle: 20 # 连接池中的最大空闲连接
#      max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    jedis:
#      pool:
#        max-active: 1024 #连接池的最大数据库连接数。设为0表示无限制
#        min-idle: 1 # 连接池中的最小空闲连接
#        max-idle: 20 #最大空闲数
#        max-wait: 10000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
#    cluster: 
#      nodes: 集群节点连接地址
#    sentinel: 
#      nodes: 节点连接地址
#      master: mymaster
#---
#### MongoDB 配置
#spring:
#  data:
#    mongodb:
#      uri: 
#---
###邮件发送相关配置
#spring: 
#  mail: 
#    host: smtp.sina.com
#    username: dllwhcrawler@sina.com
#    password: dllwhcrawler
#    default-encoding: utf-8
spring: 
  mail: 
    host: smtp.163.com
    username: dllwhdemo@163.com
    password: dllwhtest
    default-encoding: utf-8
---
###上传文件配置
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB